/**
 * The movie database
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.TheMovieDatabase) {
      root.TheMovieDatabase = {};
    }
    root.TheMovieDatabase.Posters = factory(root.TheMovieDatabase.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Posters model module.
   * @module model/Posters
   * @version 1.0.1
   */

  /**
   * Constructs a new <code>Posters</code>.
   * @alias module:model/Posters
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>Posters</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Posters} obj Optional instance to populate.
   * @return {module:model/Posters} The populated <code>Posters</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('thumbnail')) {
        obj['thumbnail'] = ApiClient.convertToType(data['thumbnail'], 'String');
      }
      if (data.hasOwnProperty('profile')) {
        obj['profile'] = ApiClient.convertToType(data['profile'], 'String');
      }
      if (data.hasOwnProperty('detailed')) {
        obj['detailed'] = ApiClient.convertToType(data['detailed'], 'String');
      }
      if (data.hasOwnProperty('original')) {
        obj['original'] = ApiClient.convertToType(data['original'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} thumbnail
   */
  exports.prototype['thumbnail'] = undefined;
  /**
   * @member {String} profile
   */
  exports.prototype['profile'] = undefined;
  /**
   * @member {String} detailed
   */
  exports.prototype['detailed'] = undefined;
  /**
   * @member {String} original
   */
  exports.prototype['original'] = undefined;



  return exports;
}));


